# default factory settings
# =================
model:
  type: RandomForestRegressor
  n_estimator: 200
  max_depth: 10

scraper:
  general:
    overwrite: None
    polite: None
  main:
    ranking:
      url: "https://www.monsterhunter.com/20th/en/vote-monster/result/"


# default paths
# =================
path:
  out: /data/result
  meta: /config/game_metadata.yaml/
  
  