game_metadata:
  freedom:
    full_title: Monster Hunter Freedom
    generation: 1
    release_order: 1
    sales: 2056818
    platforms:
      - PS2
      - PSP
      - Wii
  freedom_unite:
    full_title: Monster Hunter Freedom Unite
    generation: 2
    release_order: 2
    sales: 6892005
    platforms:
      - PS2
      - PSP
  tri:
    full_title: Monster Hunter Tri Ultimate
    generation: 3
    release_order: 3
    sales: 35224986
    platforms:
      - 3DS
      - Wii
      - Wii U
  portable:
    full_title: Monster Hunter Portable 3rd
    generation: 3
    release_order: 4
    sales: 5356436
    platforms:
      - PS3
      - PSP
  four:
    full_title: Monster Hunter 4
    generation: 4
    release_order: 5
    sales: 8300000
    platforms:
      - 3DS
  generations:
    full_title: Monster Hunter Generations Ultimate
    generation: 4
    release_order: 6
    sales: 9400000
    platforms:
      - 3DS
      - Switch
  world:
    full_title: Monster Hunter World/ Iceborne
    generation: 5
    release_order: 7
    sales: 46050000
    platforms:
      - PC
      - PS4
      - XB1
  sunbreak:
    full_title: Monster Hunter Rise/ Sunbreak
    generation: 5
    release_order: 8
    sales: 28200000
    platforms:
      - Switch
      - PC
      - PS4
      - PS5
      - XB1
      - XBS
  wilds:
    full_title: Monster Hunter Wilds
    generation: 6
    release_order: 9
    sales: 10700000
    platforms:
      - PC
      - PS5
      - XBS

# ==========================================

monster_metadata:
  top_3:
    1: Zinogre
    2: Nergigante
    3: Lagiacrus
